In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,51).reshape(5,10)

In [3]:
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [4]:
arr2=np.arange(1,101,2).reshape(5,10)

In [5]:
arr2

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [6]:
arrs=arr2

In [7]:
arrs.transpose()

array([[ 1, 21, 41, 61, 81],
       [ 3, 23, 43, 63, 83],
       [ 5, 25, 45, 65, 85],
       [ 7, 27, 47, 67, 87],
       [ 9, 29, 49, 69, 89],
       [11, 31, 51, 71, 91],
       [13, 33, 53, 73, 93],
       [15, 35, 55, 75, 95],
       [17, 37, 57, 77, 97],
       [19, 39, 59, 79, 99]])

In [18]:
#addition
print('A',arr1)
print()
print('B',arr2)
print('A+B')
print(arr1+arr2)

A [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

B [[ 1  3  5  7  9 11 13 15 17 19]
 [21 23 25 27 29 31 33 35 37 39]
 [41 43 45 47 49 51 53 55 57 59]
 [61 63 65 67 69 71 73 75 77 79]
 [81 83 85 87 89 91 93 95 97 99]]
A+B
[[  2   5   8  11  14  17  20  23  26  29]
 [ 32  35  38  41  44  47  50  53  56  59]
 [ 62  65  68  71  74  77  80  83  86  89]
 [ 92  95  98 101 104 107 110 113 116 119]
 [122 125 128 131 134 137 140 143 146 149]]


In [19]:
np.add(arr1,arr2)

array([[  2,   5,   8,  11,  14,  17,  20,  23,  26,  29],
       [ 32,  35,  38,  41,  44,  47,  50,  53,  56,  59],
       [ 62,  65,  68,  71,  74,  77,  80,  83,  86,  89],
       [ 92,  95,  98, 101, 104, 107, 110, 113, 116, 119],
       [122, 125, 128, 131, 134, 137, 140, 143, 146, 149]])

In [20]:
print(np.add(arr1,arr2))

[[  2   5   8  11  14  17  20  23  26  29]
 [ 32  35  38  41  44  47  50  53  56  59]
 [ 62  65  68  71  74  77  80  83  86  89]
 [ 92  95  98 101 104 107 110 113 116 119]
 [122 125 128 131 134 137 140 143 146 149]]


In [21]:
#matrix multiplication

In [22]:
arr1.dot(arr2)

ValueError: shapes (5,10) and (5,10) not aligned: 10 (dim 1) != 5 (dim 0)

In [26]:
arr2=np.arange(1,101,2).reshape(10,5)

In [27]:
arr2

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [28]:
arr1.dot(arr2)

array([[ 3355,  3465,  3575,  3685,  3795],
       [ 7955,  8265,  8575,  8885,  9195],
       [12555, 13065, 13575, 14085, 14595],
       [17155, 17865, 18575, 19285, 19995],
       [21755, 22665, 23575, 24485, 25395]])

In [29]:
arr2.max()

99

In [30]:
arr1.max()

50

In [31]:
arr1.mean()

25.5

In [33]:
arr1.describe

AttributeError: 'numpy.ndarray' object has no attribute 'describe'